# Generated by Django 4.1.4 on 2023-01-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_subject',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
