# Generated by Django 4.1.4 on 2023-01-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_question_q_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_subject',
            field=models.CharField(blank=True, choices=[('maths', 'MATHS'), ('science', 'SCIENCE'), ('geography', 'GEOGRAPHY'), ('english', 'ENGLISH')], max_length=25, null=True),
        ),
    ]
