# Generated by Django 4.1.5 on 2023-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_question_q_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=200),
        ),
    ]
