# Generated by Django 4.1.4 on 2023-01-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sage',
            new_name='student_age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sname',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tage',
            new_name='teacher_age',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tname',
            new_name='teacher_name',
        ),
    ]
