# Generated by Django 4.1.4 on 2023-01-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_sage_student_student_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_name',
            new_name='name',
        ),
    ]
