# Generated by Django 4.1.4 on 2023-01-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(default='Answer Here.', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='Question Here.', max_length=200),
        ),
    ]
