# Generated by Django 4.1.4 on 2023-01-10 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_question_answer_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.teacher'),
        ),
    ]
