# Generated by Django 4.1.4 on 2023-01-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
