# Generated by Django 4.1.4 on 2023-01-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
