# Generated by Django 4.1.4 on 2023-01-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_student_name_alter_teacher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.TextField(default='None', max_length=100, null=True),
        ),
    ]
