# Generated by Django 4.1.4 on 2023-01-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_student_age_alter_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='t_subject',
            field=models.CharField(choices=[('maths', 'MATHS'), ('science', 'SCIENCE'), ('geography', 'GEOGRAPHY'), ('english', 'ENGLISH')], max_length=20, null=True),
        ),
    ]
